"""Add tooth column to notes

Revision ID: 335f68fd249c
Revises: 86704d12f850
Create Date: 2025-12-29 22:14:22.483460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '335f68fd249c'
down_revision: Union[str, None] = '86704d12f850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_history', sa.Column('tooth', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('tooth', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'tooth')
    op.drop_column('note_history', 'tooth')
    # ### end Alembic commands ###
