"""add_multi_tenancy_tables

Revision ID: b45198b26479
Revises: 88de01cb3f6e
Create Date: 2026-01-27 18:24:52.935762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime, timezone

# revision identifiers, used by Alembic.
revision: str = 'b45198b26479'
down_revision: Union[str, None] = '88de01cb3f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('office_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('bills', sa.Column('office_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bills', 'offices', ['office_id'], ['id'])
    op.create_index(op.f('ix_blind_indexes_id'), 'blind_indexes', ['id'], unique=False)
    op.create_index(op.f('ix_note_embeddings_id'), 'note_embeddings', ['id'], unique=False)
    op.add_column('note_history', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('note_history', sa.Column('office_id', sa.UUID(), nullable=True))
    op.alter_column('note_history', 'edited_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'note_history', 'offices', ['office_id'], ['id'])
    op.drop_column('note_history', 'edited_at')
    op.add_column('notes', sa.Column('office_id', sa.UUID(), nullable=True))
    op.alter_column('notes', 'author_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'notes', 'offices', ['office_id'], ['id'])
    op.add_column('patients', sa.Column('office_id', sa.UUID(), nullable=True))
    op.add_column('patients', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'patients', 'offices', ['office_id'], ['id'])
    op.add_column('quick_phrases', sa.Column('office_id', sa.UUID(), nullable=True))
    op.alter_column('quick_phrases', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_quick_phrases_category'), 'quick_phrases', ['category'], unique=False)
    op.create_index(op.f('ix_quick_phrases_id'), 'quick_phrases', ['id'], unique=False)
    op.create_foreign_key(None, 'quick_phrases', 'offices', ['office_id'], ['id'])
    op.add_column('tasks', sa.Column('office_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'offices', ['office_id'], ['id'])
    op.add_column('visits', sa.Column('office_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'visits', 'offices', ['office_id'], ['id'])
    
    # --- Data Migration: Backfill Legacy Office ---
    # 1. Define Legacy Office ID
    legacy_office_id = '00000000-0000-0000-0000-000000000000'
    
    # 2. Insert Legacy Office
    offices_table = sa.table('offices',
        sa.Column('id', sa.UUID()),
        sa.Column('name', sa.String()),
        sa.Column('created_at', sa.DateTime(timezone=True))
    )
    
    op.bulk_insert(offices_table, [
        {
            'id': legacy_office_id, 
            'name': 'Legacy Office', 
            'created_at': datetime.now(timezone.utc)
        }
    ])
    
    # 3. Update existing records
    op.execute(f"UPDATE patients SET office_id = '{legacy_office_id}' WHERE office_id IS NULL")
    op.execute(f"UPDATE notes SET office_id = '{legacy_office_id}' WHERE office_id IS NULL")
    op.execute(f"UPDATE note_history SET office_id = '{legacy_office_id}' WHERE office_id IS NULL")
    op.execute(f"UPDATE visits SET office_id = '{legacy_office_id}' WHERE office_id IS NULL")
    op.execute(f"UPDATE bills SET office_id = '{legacy_office_id}' WHERE office_id IS NULL")
    op.execute(f"UPDATE tasks SET office_id = '{legacy_office_id}' WHERE office_id IS NULL")
    op.execute(f"UPDATE quick_phrases SET office_id = '{legacy_office_id}' WHERE office_id IS NULL")
    # ---------------------------------------------
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_column('visits', 'office_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_column('tasks', 'office_id')
    op.drop_constraint(None, 'quick_phrases', type_='foreignkey')
    op.drop_index(op.f('ix_quick_phrases_id'), table_name='quick_phrases')
    op.drop_index(op.f('ix_quick_phrases_category'), table_name='quick_phrases')
    op.alter_column('quick_phrases', 'text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('quick_phrases', 'office_id')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'is_active')
    op.drop_column('patients', 'office_id')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.alter_column('notes', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('notes', 'author_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('notes', 'office_id')
    op.add_column('note_history', sa.Column('edited_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'note_history', type_='foreignkey')
    op.alter_column('note_history', 'edited_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('note_history', 'office_id')
    op.drop_column('note_history', 'created_at')
    op.drop_index(op.f('ix_note_embeddings_id'), table_name='note_embeddings')
    op.drop_index(op.f('ix_blind_indexes_id'), table_name='blind_indexes')
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_column('bills', 'office_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('offices')
    # ### end Alembic commands ###
